export const Fetch_SUGGESTIONS = 'FETCH_SUGGESTIONS';

export const UPDATE_SELECTED_MEDICINE_START = 'UPDATE_SELECTED_MEDICINE_START';
export const UPDATE_SELECTED_MEDICINE = 'UPDATE_SELECTED_MEDICINE';

export const FETCH_SINGLE_DRUG_PRICE_START = 'FETCH_SINGLE_DRUG_PRICE_START';
export const FETCH_SINGLE_DRUG_PRICE_SUCCESS = 'FETCH_SINGLE_DRUG_PRICE_SUCCESS';
