export const Fetch_SUGGESTIONS = 'FETCH_SUGGESTIONS';

export const UPDATE_SELECTED_MEDICINE_START = 'UPDATE_SELECTED_MEDICINE_START';
export const UPDATE_SELECTED_MEDICINE = 'UPDATE_SELECTED_MEDICINE';

export const FETCH_FINALMED_START = 'FETCH_FETCH_FINALMED_START';
export const FETCH_FINALMED_SUCCESS = 'FETCH_FINALMED_SUCCESS';

export const PUSH_USERINPUT = 'PUSH_USERINPUT'
export const POP_USERINPUT = 'POP_USERINPUT'
export const FETCH_PRESCRIPTIONPRICE_START = 'FETCH_PRESCRIPTIONPRICE_START'
export const FETCH_PRESCRIPTIONPRICE_SUCCESS = 'FETCH_PRESCRIPTIONPRICE_SUCCESS'