export const Fetch_SUGGESTIONS = 'FETCH_SUGGESTIONS';

export const FETCH_SINGLE_DRUG_PRICE_START = 'FETCH_SINGLE_DRUG_PRICE_START';
export const FETCH_SINGLE_DRUG_PRICE_SUCCESS = 'FETCH_SINGLE_DRUG_PRICE_SUCCESS';
